# Use an official MongoDB image as a parent image
FROM mongo:latest

# Set the working directory to /data/db
WORKDIR /data/db

# Expose the default MongoDB port
EXPOSE 27017

# Start the MongoDB server
CMD ["mongod"]
